FROM mambaorg/micromamba:bookworm-slim

WORKDIR /src

COPY --chown=$MAMBA_USER:$MAMBA_USER package.yaml /tmp/freeze_env.yaml
RUN micromamba env create --yes --file /tmp/freeze_env.yaml && micromamba clean --all --yes
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_ACTIVATE_ENVIRONMENT=interview-sim-server

COPY . .
COPY gunicorn.conf.py .

CMD ["micromamba", "run", "-n", "interview-sim-server", "gunicorn", "app.main:app", "--config", "gunicorn.conf.py"]