FROM mambaorg/micromamba:latest

USER $MAMBA_USER
WORKDIR /src

COPY --chown=$MAMBA_USER:$MAMBA_USER package.yaml /tmp/freeze_env.yaml
RUN micromamba env create --yes --file /tmp/freeze_env.yaml && micromamba clean --all --yes
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_ACTIVATE_ENVIRONMENT=interview-sim-server

ENV JAVA_HOME=/opt/conda/envs/interview-sim-server
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN java -version && echo "Java Home: $JAVA_HOME"

COPY . .
COPY gunicorn.conf.py .

CMD ["micromamba", "run", "-n", "interview-sim-server", "gunicorn", "app.main:app", "--config", "gunicorn.conf.py"]