name: interview-sim-server
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23
  - fastapi>=0.111
  - uvicorn
  - pydantic>=2.7,<3
  - httpx
  - gunicorn
  - pip:
      - openai
      - python-dotenv
      - python-multipart
      - langchain-openai>=0.2.0
      - pyyaml
      - langchain>=0.2
      - langchain-community
      - langchain-anthropic
      - langgraph>=0.2
      - langgraph-checkpoint-sqlite
      - requests
      - loguru
      - coloredlogs
      - python-json-logger
      - prometheus-fastapi-instrumentator
      - gTTS
      - sentence-transformers
      - redis==5.0.7
      - langchain-deepseek
      - langchain-community
      - langchain-anthropic
      - langgraph
      - langgraph-checkpoint-sqlite
      - requests
      - loguru
      - coloredlogs
      - python-json-logger
      - prometheus-fastapi-instrumentator
      - gTTS
      - sentence-transformers
